import type { Product } from "../types";

/**
 * Seeded catalogue.
 *
 * Placeholder *product* data rather than marketing copy, so it can carry real
 * numbers without inventing claims: case diameters, lug-to-lug figures and calibre
 * specs are the merchandise itself, and nothing here attributes a specification to
 * a real manufacturer. All references are house references.
 *
 * Replace with your Prisma query in `lib/catalog/repository.ts`. Nothing downstream
 * of that file needs to change.
 */

const DIAL = {
  silverSunburst: {
    id: "dial-silver",
    name: "Silver sunburst",
    colorName: "Silver",
    colorHex: "#C9C6BE",
    finish: "sunburst",
    priceDeltaInCents: 0,
    complications: ["date"],
    complicationPlacements: { date: "window" },
  },
  blackMatte: {
    id: "dial-black",
    name: "Black matte",
    colorName: "Black",
    colorHex: "#191919",
    finish: "matte",
    priceDeltaInCents: 0,
    complications: [],
    complicationPlacements: {},
  },
  blackSunburst: {
    id: "dial-black-sunburst",
    name: "Black sunburst",
    colorName: "Black",
    colorHex: "#141414",
    finish: "sunburst",
    priceDeltaInCents: 18000,
    complications: ["date"],
    complicationPlacements: { date: "window" },
  },
  champagne: {
    id: "dial-champagne",
    name: "Champagne",
    colorName: "Champagne",
    colorHex: "#CDB489",
    finish: "sunburst",
    priceDeltaInCents: 24000,
    complications: ["date"],
    complicationPlacements: { date: "window" },
  },
  ivory: {
    id: "dial-ivory",
    name: "Ivory lacquer",
    colorName: "Ivory",
    colorHex: "#E5DFD0",
    finish: "lacquered",
    priceDeltaInCents: 32000,
    complications: [],
    complicationPlacements: {},
  },
  slate: {
    id: "dial-slate",
    name: "Slate grey",
    colorName: "Slate",
    colorHex: "#4A4E52",
    finish: "sunburst",
    priceDeltaInCents: 0,
    complications: ["date"],
    complicationPlacements: { date: "window" },
  },
  forest: {
    id: "dial-forest",
    name: "Forest green",
    colorName: "Forest",
    colorHex: "#22392E",
    finish: "guilloche",
    priceDeltaInCents: 42000,
    complications: ["small-seconds"],
    complicationPlacements: { "small-seconds": "subdial" },
  },
  oxblood: {
    id: "dial-oxblood",
    name: "Oxblood",
    colorName: "Oxblood",
    colorHex: "#4A1F22",
    finish: "sunburst",
    priceDeltaInCents: 28000,
    complications: ["date"],
    complicationPlacements: { date: "window" },
  },
  midnightBlue: {
    id: "dial-midnight",
    name: "Midnight blue",
    colorName: "Midnight",
    colorHex: "#16233A",
    finish: "sunburst",
    priceDeltaInCents: 36000,
    complications: ["gmt"],
    complicationPlacements: { gmt: "inner-ring" },
  },
  salmon: {
    id: "dial-salmon",
    name: "Salmon",
    colorName: "Salmon",
    colorHex: "#D2A38C",
    finish: "salmon",
    priceDeltaInCents: 26000,
    complications: ["small-seconds"],
    complicationPlacements: { "small-seconds": "subdial" },
  },
  white: {
    id: "dial-white",
    name: "White",
    colorName: "White",
    colorHex: "#EDEAE2",
    finish: "matte",
    priceDeltaInCents: 0,
    complications: ["date"],
    complicationPlacements: { date: "window" },
  },
  carbon: {
    id: "dial-carbon",
    name: "Carbon grey",
    colorName: "Carbon",
    colorHex: "#2B2E2D",
    finish: "guilloche",
    priceDeltaInCents: 0,
    complications: ["chronograph"],
    complicationPlacements: { chronograph: "subdial" },
  },
} as const;

const STRAP = {
  steel: (id: string, name: string, colorHex: string, widthMm: number, delta = 0) => ({
    id: `strap-${id}`,
    type: "bracelet" as const,
    name,
    material: "316L stainless steel, three-link",
    colorHex,
    colorName: name,
    priceDeltaInCents: delta,
    widthMm,
  }),
  leather: (id: string, name: string, colorHex: string, widthMm: number, stitch?: string) => ({
    id: `strap-${id}`,
    type: "leather" as const,
    name,
    material: "Full-grain calfskin, hand-stitched",
    colorHex,
    colorName: name,
    priceDeltaInCents: -12000,
    widthMm,
    stitchColorHex: stitch,
  }),
  rubber: (id: string, name: string, colorHex: string, widthMm: number) => ({
    id: `strap-${id}`,
    type: "rubber" as const,
    name,
    material: "FKM rubber, vulcanised",
    colorHex,
    colorName: name,
    priceDeltaInCents: -8000,
    widthMm,
  }),
  nato: (id: string, name: string, colorHex: string, widthMm: number) => ({
    id: `strap-${id}`,
    type: "nato" as const,
    name,
    material: "Woven nylon, pass-through",
    colorHex,
    colorName: name,
    priceDeltaInCents: -18000,
    widthMm,
  }),
  perforated: (id: string, name: string, colorHex: string, widthMm: number) => ({
    id: `strap-${id}`,
    type: "perforated" as const,
    name,
    material: "Perforated calfskin rally strap",
    colorHex,
    colorName: name,
    priceDeltaInCents: -4000,
    widthMm,
  }),
  mesh: (id: string, name: string, colorHex: string, widthMm: number) => ({
    id: `strap-${id}`,
    type: "mesh" as const,
    name,
    material: "Woven 316L steel mesh, adjustable",
    colorHex,
    colorName: name,
    priceDeltaInCents: 8000,
    widthMm,
  }),
} as const;

export const PRODUCTS: Product[] = [
  {
    id: "p-meridian-38",
    slug: "meridian-38",
    brand: "Chronos & Steel",
    model: "Meridian 38",
    reference: "CS-380",
    yearIntroduced: 2019,
    collection: "Meridian",
    summary: "The 38 mm that started the house, and still the one we make most of.",
    story: "We sized the Meridian against a rule we still hold to: it should pass under a shirt cuff without being noticed, and it should not disappear when you take it off. That is 38.0 mm, and no less. The case is 9.1 mm thick because the calibre beneath it is a thin one, and we have never fitted a larger movement to make a number on a spec sheet look better.\n\nThe dial is the argument. Applied indices are cut and polished separately, then set by hand; the lume is Super-LumiNova BGW9, graded twice so the minute track reads brighter than the hour batons at 3 a.m. The sapphire is double-domed, which costs us two millimetres of thickness and buys a dial that appears to sit under glass rather than inside it.",
    caseSpec: {
      diameterMm: 38.0,
      thicknessMm: 9.1,
      lugToLugMm: 45.2,
      lugWidthMm: 19,
      material: "stainless-steel",
      finish: "polished",
      bezel: "smooth",
      crystal: "domed-sapphire",
      waterResistanceM: 50,
    },
    movement: {
      type: "automatic",
      caliber: "CS-114",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 56,
      frequencyVph: 28800,
      jewels: 27,
      components: 231,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.silverSunburst, DIAL.blackMatte, DIAL.ivory],
    straps: [
      STRAP.steel("steel-38", "Steel bracelet", "#B7B4AC", 19),
      STRAP.leather("calf-38-tan", "Tan calfskin", "#6B4A2B", 19, "#C9A227"),
      STRAP.nato("nato-38-olive", "Olive NATO", "#4A5138", 19),
    ],
    indexStyle: "baton",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "NEUCHÂTEL",
    basePriceInCents: 485000,
    currency: "USD",
    stock: 6,
    reserved: 1,
    editionSize: null,
    featured: true,
    tags: ["dress", "everyday", "thin"],
  },
  {
    id: "p-meridian-41",
    slug: "meridian-41",
    brand: "Chronos & Steel",
    model: "Meridian 41",
    reference: "CS-410",
    yearIntroduced: 2021,
    collection: "Meridian",
    summary: "The Meridian at wrist size, for those who found 38 mm small.",
    story: "We did not scale the 38. A scaled watch is a compromise with a decimal point, and the proportions that make a 38 read elegantly do not survive being multiplied. The 41 is a separate case drawing, with a longer flank and a bezel that steps down more sharply, so the dial still sits high in the case rather than floating in a wide bezel.\n\nThe calibre is the same CS-114, undecorated. We resisted putting a rotor design on this one for a long time, on the grounds that an empty caseback is better than a disappointing one.",
    caseSpec: {
      diameterMm: 41.0,
      thicknessMm: 9.4,
      lugToLugMm: 48.6,
      lugWidthMm: 20,
      material: "stainless-steel",
      finish: "brushed",
      bezel: "smooth",
      crystal: "domed-sapphire",
      waterResistanceM: 100,
    },
    movement: {
      type: "automatic",
      caliber: "CS-114",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 56,
      frequencyVph: 28800,
      jewels: 27,
      components: 231,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.blackSunburst, DIAL.slate, DIAL.ivory],
    straps: [
      STRAP.steel("steel-41", "Steel bracelet", "#B0ADA5", 20),
      STRAP.leather("calf-41-navy", "Navy calfskin", "#1E2A44", 20, "#C9C4B8"),
      STRAP.perforated("rally-41", "Black rally", "#1C1C1C", 20),
    ],
    indexStyle: "baton",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "NEUCHÂTEL",
    basePriceInCents: 520000,
    currency: "USD",
    stock: 4,
    reserved: 0,
    editionSize: null,
    featured: false,
    tags: ["dress", "everyday"],
  },
  {
    id: "p-nocturne-moon",
    slug: "nocturne-moonphase",
    brand: "Chronos & Steel",
    model: "Nocturne Moonphase",
    reference: "CS-392",
    yearIntroduced: 2022,
    collection: "Nocturne",
    summary: "A moonphase accurate to a day in 122 years, in a 39 mm case.",
    story: "The moonphase is a 135-tooth wheel driving a 59.7-tooth cam, which gives one uncorrected day of drift in 122 years. We have seen the aperture opened at the wrong phase often enough to know this is the part of a moonphase that matters, so it is the part we test.\n\nThe disc is printed in-house on a 0.3 mm brass blank, which is why the disc has a very slightly warm cast in daylight and a very slightly cold one under tungsten. We have stopped apologising for this.",
    caseSpec: {
      diameterMm: 39.0,
      thicknessMm: 10.8,
      lugToLugMm: 46.9,
      lugWidthMm: 20,
      material: "stainless-steel",
      finish: "polished",
      bezel: "smooth",
      crystal: "sapphire",
      waterResistanceM: 50,
    },
    movement: {
      type: "automatic",
      caliber: "CS-226",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 68,
      frequencyVph: 28800,
      jewels: 31,
      components: 288,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.oxblood, DIAL.midnightBlue, DIAL.blackMatte],
    straps: [
      STRAP.steel("steel-39", "Steel bracelet", "#B4B1A9", 20),
      STRAP.leather("alligator-39-burg", "Burgundy alligator", "#4A1F22", 20, "#8A6A4A"),
      STRAP.leather("calf-39-black", "Black calfskin", "#1B1B1B", 20, "#6E6A62"),
    ],
    indexStyle: "dauphine",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "NOCTURNE",
    basePriceInCents: 1280000,
    currency: "USD",
    stock: 2,
    reserved: 1,
    editionSize: 60,
    featured: true,
    tags: ["dress", "complication", "evening"],
  },
  {
    id: "p-longitude-gmt",
    slug: "longitude-gmt",
    brand: "Chronos & Steel",
    model: "Longitude GMT",
    reference: "CS-402",
    yearIntroduced: 2023,
    collection: "Longitude",
    summary: "A true second time zone on a 24-hour ring, jumping the hour independently.",
    story: "Most GMT watches move the 24-hour hand once every 24 hours and call it a second time zone. This one jumps the hour hand on demand, which is what a travelling watch actually needs: you change zones and the local time changes with you, without waiting for midnight and without setting the movement.\n\nThe jump is operated through a clutch on the crown, and the 24-hour ring is engraved rather than printed so the numerals for 14 through 22 stay crisp at 0.4 mm.",
    caseSpec: {
      diameterMm: 40.0,
      thicknessMm: 11.2,
      lugToLugMm: 47.8,
      lugWidthMm: 20,
      material: "stainless-steel",
      finish: "brushed",
      bezel: "coin-edge",
      crystal: "sapphire",
      waterResistanceM: 100,
    },
    movement: {
      type: "automatic",
      caliber: "CS-405",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 70,
      frequencyVph: 28800,
      jewels: 34,
      components: 312,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.midnightBlue, DIAL.blackMatte, DIAL.forest],
    straps: [
      STRAP.steel("steel-40", "Steel bracelet", "#ADAAA2", 20),
      STRAP.leather("calf-40-tan", "Tan calfskin", "#6B4A2B", 20, "#C9A227"),
      STRAP.rubber("rubber-40", "Black rubber", "#1A1A1A", 20),
    ],
    indexStyle: "baton",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "LONGITUDE",
    basePriceInCents: 1120000,
    currency: "USD",
    stock: 3,
    reserved: 0,
    editionSize: 120,
    featured: true,
    tags: ["travel", "complication", "tool"],
  },
  {
    id: "p-calibre-114-chrono",
    slug: "calibre-114-chronograph",
    brand: "Chronos & Steel",
    model: "Calibre 114 Chronograph",
    reference: "CS-410-C",
    yearIntroduced: 2020,
    collection: "Calibre",
    summary: "A column-wheel chronograph with a lateral clutch and 60 hours in reserve.",
    story: "The column wheel and lateral clutch add about 1.7 mm of thickness over the three-hand CS-114. We publish that number because the alternative is a chronograph that claims 9 mm and measures 11.\n\nStarting the chronograph reads as a distinct click rather than a soft sweep, which is the entire argument for a column wheel over an instantaneous one. The pushers are screw-down and sealed to 100 m, which is a genuine complication for a chronograph and not a marketing adjective.",
    caseSpec: {
      diameterMm: 40.0,
      thicknessMm: 13.4,
      lugToLugMm: 48.2,
      lugWidthMm: 21,
      material: "stainless-steel",
      finish: "brushed",
      bezel: "smooth",
      crystal: "sapphire",
      waterResistanceM: 100,
    },
    movement: {
      type: "automatic",
      caliber: "CS-114C",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 60,
      frequencyVph: 28800,
      jewels: 39,
      components: 344,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.carbon, DIAL.white, DIAL.silverSunburst],
    straps: [
      STRAP.steel("steel-40c", "Steel bracelet", "#B1AEA6", 21),
      STRAP.perforated("rally-40c", "Black rally", "#1B1B1B", 21),
      STRAP.leather("calf-40c-tan", "Tan calfskin", "#6B4A2B", 21, "#C9A227"),
    ],
    indexStyle: "baton",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "CHRONOGRAPH",
    basePriceInCents: 940000,
    currency: "USD",
    stock: 5,
    reserved: 2,
    editionSize: null,
    featured: false,
    tags: ["chronograph", "complication", "tool"],
  },
  {
    id: "p-vantage-dive",
    slug: "vantage-dive",
    brand: "Chronos & Steel",
    model: "Vantage Dive",
    reference: "CS-420",
    yearIntroduced: 2020,
    collection: "Vantage",
    summary: "A 300 m diver with a 120-tooth unidirectional bezel and a lume index you can find in the dark.",
    story: "The bezel has 120 teeth, which means each click is three degrees, which means the elapsed time is readable to five minutes without squinting. Sixty-tooth bezels are the industry default because they are cheaper; the difference is one minute of resolution per click.\n\nThe lume is a two-compound grade: C3 on the indices, C5 on the bezel pearl, so the bezel and the dial read at visibly different brightness, and the bezel is the one that should win.",
    caseSpec: {
      diameterMm: 42.0,
      thicknessMm: 12.6,
      lugToLugMm: 50.1,
      lugWidthMm: 21,
      material: "stainless-steel",
      finish: "bead-blasted",
      bezel: "dive",
      crystal: "sapphire",
      waterResistanceM: 300,
    },
    movement: {
      type: "automatic",
      caliber: "CS-121",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 65,
      frequencyVph: 28800,
      jewels: 26,
      components: 246,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.blackMatte, DIAL.midnightBlue, DIAL.forest],
    straps: [
      STRAP.steel("steel-42", "Steel bracelet", "#A9A69E", 21),
      STRAP.rubber("rubber-42", "Black rubber", "#181818", 21),
      STRAP.nato("nato-42", "Olive NATO", "#4A5138", 21),
    ],
    indexStyle: "minimal",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "VANTAGE 300",
    basePriceInCents: 720000,
    currency: "USD",
    stock: 8,
    reserved: 3,
    editionSize: null,
    featured: true,
    tags: ["dive", "tool", "sport"],
  },
  {
    id: "p-vantage-44",
    slug: "vantage-44",
    brand: "Chronos & Steel",
    model: "Vantage 44",
    reference: "CS-440",
    yearIntroduced: 2022,
    collection: "Vantage",
    summary: "A 44 mm that wears smaller than it measures, because we moved the lug line in.",
    story: "A 44 mm case is only as long as its lug-to-lug, and most 44s measure 52 mm or more because the lugs are drawn straight out from the caseband. We angled ours downward by 14 degrees, which brings the lug-to-lug down to 49.4 mm without reducing the case diameter or the lug width.\n\nThis is the single most useful thing we have done to a case in ten years, and it cost nothing to manufacture.",
    caseSpec: {
      diameterMm: 44.0,
      thicknessMm: 12.1,
      lugToLugMm: 49.4,
      lugWidthMm: 22,
      material: "stainless-steel",
      finish: "brushed",
      bezel: "smooth",
      crystal: "sapphire",
      waterResistanceM: 200,
    },
    movement: {
      type: "automatic",
      caliber: "CS-121",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 65,
      frequencyVph: 28800,
      jewels: 26,
      components: 246,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.slate, DIAL.blackSunburst, DIAL.champagne],
    straps: [
      STRAP.steel("steel-44", "Steel bracelet", "#ADAAA2", 22),
      STRAP.leather("calf-44-tan", "Tan calfskin", "#6B4A2B", 22, "#C9A227"),
      STRAP.perforated("rally-44", "Black rally", "#1B1B1B", 22),
    ],
    indexStyle: "baton",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "VANTAGE",
    basePriceInCents: 640000,
    currency: "USD",
    stock: 7,
    reserved: 1,
    editionSize: null,
    featured: false,
    tags: ["everyday", "large", "sport"],
  },
  {
    id: "p-reserve-power",
    slug: "reserve-power",
    brand: "Chronos & Steel",
    model: "Reserve",
    reference: "CS-370",
    yearIntroduced: 2018,
    collection: "Meridian",
    summary: "Hand-wound, 4.2 mm thin, with a power reserve you can read in seconds.",
    story: "A 72-hour reserve on a hand-wound 9.2 mm movement is a reasonable engineering target. A 72-hour reserve on a hand-wound 4.2 mm movement is the one we set out to beat, and the barrel is a single mainspring rather than a stacked pair, which is why the torque curve is flatter than a twin-barrel reserve of the same duration.\n\nThe reserve indicator is a sector from 0 to 72 hours, and the last third is marked in a warmer tone so the reading is legible in peripheral vision. You should not have to look directly at it to know roughly how much is left.",
    caseSpec: {
      diameterMm: 37.0,
      thicknessMm: 4.2,
      lugToLugMm: 44.0,
      lugWidthMm: 18,
      material: "white-gold",
      finish: "polished",
      bezel: "smooth",
      crystal: "domed-sapphire",
      waterResistanceM: 30,
    },
    movement: {
      type: "manual",
      caliber: "CS-081",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 72,
      frequencyVph: 21600,
      jewels: 19,
      components: 132,
      chronometerDeviationPercent: null,
      winding: "hand-wound",
    },
    dials: [DIAL.ivory, DIAL.silverSunburst, DIAL.white],
    straps: [
      STRAP.leather("calf-37-tan", "Tan calfskin", "#6B4A2B", 18, "#C9A227"),
      STRAP.leather("calf-37-black", "Black calfskin", "#1C1C1C", 18, "#6E6A62"),
      // A 19 mm strap on an 18 mm case. The configurator must not offer this
      // pairing, and reconciling a strap change has to fall back to an 18 mm.
      STRAP.leather("calf-37-19mm", "Chestnut, 19 mm", "#5A3A22", 19, "#C9A227"),
    ],
    indexStyle: "arabic",
    lume: false,
    signature: "CHRONOS & STEEL",
    sublabel: "RÉSERVE DE MARCHE",
    basePriceInCents: 1680000,
    currency: "USD",
    stock: 1,
    reserved: 0,
    editionSize: 75,
    featured: true,
    tags: ["dress", "thin", "hand-wound", "formal"],
  },
  {
    id: "p-sector-quartz",
    slug: "sector-quartz",
    brand: "Chronos & Steel",
    model: "Sector",
    reference: "CS-360",
    yearIntroduced: 2017,
    collection: "Sector",
    summary: "A battery quartz with small seconds, because not every watch needs a rotor.",
    story: "A quartz movement with a small-seconds hand and no date window, in a 36 mm case, is a harder thing to design than an automatic with three complications. The seconds hand has to be balanced enough not to stutter, the dial has to be legible without lume, and the train has to be quiet.\n\nThe 36 mm sector dial uses a railroad minute track, which came back because we kept putting it on older watches and kept being asked what it was. It is a railway clock face. That is the whole idea.",
    caseSpec: {
      diameterMm: 36.0,
      thicknessMm: 7.4,
      lugToLugMm: 43.1,
      lugWidthMm: 18,
      material: "stainless-steel",
      finish: "polished",
      bezel: "smooth",
      crystal: "mineral",
      waterResistanceM: 30,
    },
    movement: {
      type: "quartz",
      caliber: "CS-Q04",
      manufacturer: "Chronos & Steel",
      powerReserveHours: null,
      frequencyVph: null,
      jewels: null,
      components: 64,
      chronometerDeviationPercent: null,
      winding: "quartz",
    },
    dials: [DIAL.white, DIAL.blackMatte, DIAL.salmon],
    straps: [
      STRAP.leather("calf-36-black", "Black calfskin", "#1C1C1C", 18, "#6E6A62"),
      STRAP.leather("calf-36-brown", "Chestnut calfskin", "#5A3A22", 18, "#C9A227"),
      STRAP.nato("nato-36-navy", "Navy NATO", "#22304F", 18),
      STRAP.mesh("mesh-36", "Steel mesh", "#B5B2AA", 18),
    ],
    indexStyle: "arabic",
    lume: false,
    signature: "CHRONOS & STEEL",
    sublabel: "SECTOR",
    basePriceInCents: 285000,
    currency: "USD",
    stock: 14,
    reserved: 2,
    editionSize: null,
    featured: false,
    tags: ["dress", "affordable", "quartz", "small"],
  },
  {
    id: "p-bronze-field",
    slug: "bronze-field",
    brand: "Chronos & Steel",
    model: "Field 39 Bronze",
    reference: "CS-390-BR",
    yearIntroduced: 2021,
    collection: "Field",
    summary: "CuAl9Ni3Fe2 bronze, which will not match any other case on the shelf.",
    story: "Bronze is not a finish, it is an alloy that changes. A CuAl9Ni3Fe2 case arrives as a pale gold and is somewhere else entirely after a summer on a wrist in salt air. We do not guarantee how yours will look, and we do not photograph ours in a flattering stage of its life.\n\nThe case is 39 mm because bronze is heavy at 12.4 g for the middle case alone, and a larger bronze watch is a wrist weight, not a wrist watch.",
    caseSpec: {
      diameterMm: 39.0,
      thicknessMm: 11.6,
      lugToLugMm: 47.4,
      lugWidthMm: 20,
      material: "bronze",
      finish: "sandblasted",
      bezel: "smooth",
      crystal: "sapphire",
      waterResistanceM: 150,
    },
    movement: {
      type: "automatic",
      caliber: "CS-121",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 65,
      frequencyVph: 28800,
      jewels: 26,
      components: 246,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.blackMatte, DIAL.forest, DIAL.carbon],
    straps: [
      STRAP.leather("calf-39-olive", "Olive calfskin", "#4A5138", 20, "#C9C4B8"),
      STRAP.nato("nato-39-khaki", "Khaki NATO", "#6B6248", 20),
      STRAP.rubber("rubber-39", "Black rubber", "#191919", 20),
    ],
    indexStyle: "arabic",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "FIELD",
    basePriceInCents: 680000,
    currency: "USD",
    stock: 5,
    reserved: 1,
    editionSize: null,
    featured: true,
    tags: ["field", "tool", "patina"],
  },
  {
    id: "p-titan-gmt",
    slug: "titan-gmt",
    brand: "Chronos & Steel",
    model: "Titan GMT",
    reference: "CS-422-TI",
    yearIntroduced: 2023,
    collection: "Longitude",
    summary: "43 mm of GMT in titanium, at 51 grams including the bracelet.",
    story: "Titanium is 43 percent lighter than 316L steel and considerably more difficult to polish, because it does not take a bright finish without being worked at for a long time. Our cases are brushed, with polished chamfers only where the chamfer already exists in the machining. The bevel is not added afterwards, it is left.\n\nAt 51 g on the bracelet this is the only watch we make that you can wear on a wrist all day and then forget is there. That is a design constraint we set deliberately.",
    caseSpec: {
      diameterMm: 43.0,
      thicknessMm: 11.9,
      lugToLugMm: 50.6,
      lugWidthMm: 21,
      material: "titanium",
      finish: "bead-blasted",
      bezel: "coin-edge",
      crystal: "sapphire",
      waterResistanceM: 100,
    },
    movement: {
      type: "automatic",
      caliber: "CS-405",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 70,
      frequencyVph: 28800,
      jewels: 34,
      components: 312,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.midnightBlue, DIAL.blackMatte, DIAL.forest],
    straps: [
      STRAP.steel("ti-42", "Titanium bracelet", "#A6A39B", 21),
      STRAP.rubber("rubber-42b", "Black rubber", "#181818", 21),
      STRAP.nato("nato-42b", "Olive NATO", "#4A5138", 21),
    ],
    indexStyle: "minimal",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "TITAN GMT",
    basePriceInCents: 1860000,
    currency: "USD",
    stock: 3,
    reserved: 0,
    editionSize: 200,
    featured: false,
    tags: ["travel", "light", "complication", "sport"],
  },
  {
    id: "p-ceramic-mono",
    slug: "ceramic-mono-push",
    brand: "Chronos & Steel",
    model: "Ceramic Mono-Push",
    reference: "CS-410-CE",
    yearIntroduced: 2024,
    collection: "Calibre",
    summary: "A 41 mm ceramic chronograph with a single pusher and no pushers at all.",
    story: "A monopusher chronograph is a 0:05 stopwatch. You press once at the start and once at the finish, and the total is read off a totaliser. It is the chronograph for a sport where you care about the whole elapsed time rather than a lap: a race, a crossing, a dive.\n\nThe case is zirconia ceramic, bead-blasted, with a caseback in titanium so the movement is not cased in a material that will scratch a movement. That detail costs more than the ceramic saved.",
    caseSpec: {
      diameterMm: 41.0,
      thicknessMm: 12.2,
      lugToLugMm: 48.9,
      lugWidthMm: 21,
      material: "ceramic",
      finish: "bead-blasted",
      bezel: "tachymeter",
      crystal: "sapphire",
      waterResistanceM: 100,
    },
    movement: {
      type: "automatic",
      caliber: "CS-114M",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 60,
      frequencyVph: 28800,
      jewels: 37,
      components: 328,
      chronometerDeviationPercent: null,
      winding: "self-winding",
    },
    dials: [DIAL.carbon, DIAL.white, DIAL.midnightBlue],
    straps: [
      STRAP.rubber("rubber-41c", "Black rubber", "#171717", 21),
      STRAP.steel("steel-41c", "Steel bracelet", "#AEABA6", 21),
      STRAP.perforated("rally-41c", "Black rally", "#1A1A1A", 21),
    ],
    indexStyle: "minimal",
    lume: true,
    signature: "CHRONOS & STEEL",
    sublabel: "MONO-PUSH",
    basePriceInCents: 2450000,
    currency: "USD",
    stock: 2,
    reserved: 1,
    editionSize: 90,
    featured: false,
    tags: ["chronograph", "sport", "complication", "light"],
  },
  {
    id: "p-observatory-gmt",
    slug: "observatory-gmt",
    brand: "Chronos & Steel",
    model: "Observatory",
    reference: "CS-390-G",
    yearIntroduced: 2024,
    collection: "Nocturne",
    summary: "39 mm, guilloché dial, and a chronometer certificate in every box.",
    story: "This is the only watch in the collection that leaves with a COSC certificate as standard, and we publish the measured deviation on the spec sheet rather than describing the movement as chronometer-grade. The CS-114T is adjusted in five positions and tested over fifteen days, and the figure on your certificate is the figure on your watch, not a figure on a website.\n\nThe dial is engine-turned on a rose engine we built for this one pattern. There are 400 grooves and the pattern is not radially symmetrical on purpose, so the guilloché catches light in a way that moves as the wrist turns.",
    caseSpec: {
      diameterMm: 39.0,
      thicknessMm: 10.4,
      lugToLugMm: 46.5,
      lugWidthMm: 20,
      material: "stainless-steel",
      finish: "polished",
      bezel: "fluted",
      crystal: "domed-sapphire",
      waterResistanceM: 50,
    },
    movement: {
      type: "automatic",
      caliber: "CS-114T",
      manufacturer: "Chronos & Steel, Neuchâtel",
      powerReserveHours: 56,
      frequencyVph: 28800,
      jewels: 27,
      components: 231,
      chronometerDeviationPercent: 2.8,
      winding: "self-winding",
    },
    dials: [DIAL.forest, DIAL.silverSunburst, DIAL.oxblood],
    straps: [
      STRAP.leather("alligator-39-forest", "Forest alligator", "#22392E", 20, "#8A6A4A"),
      STRAP.steel("steel-39o", "Steel bracelet", "#B2AFA7", 20),
      STRAP.leather("calf-39o-sand", "Sand calfskin", "#B6A78C", 20, "#6B5B44"),
    ],
    indexStyle: "roman",
    lume: false,
    signature: "CHRONOS & STEEL",
    sublabel: "OBSERVATOIRE",
    basePriceInCents: 4200000,
    currency: "USD",
    stock: 1,
    reserved: 0,
    editionSize: 40,
    featured: false,
    tags: ["dress", "chronometer", "guilloche", "formal"],
  },
];

export const COLLECTIONS = Array.from(
  new Set(PRODUCTS.map((product) => product.collection)),
).sort();
